### ISSUE TITLE
Ruby Sintaxy extends

### ISSUE THREAD

**Issue by aristotelesbr** [davidosomething/vim-colors-meh#2]
hello would it be possible to extend the syntax for ruby ​ ❤️  ​language? :)

**Comment by davidosomething** [comment]
it should be fine for all languages
Vim colorschemes work by defining mappings like

```
hi Normal guifg=#ff0000 guibg=#000000
```

Syntax highlighting files usually just use these mappings like variables, e.g. ruby might have something like

```
hi rubySpecialSymbols link Normal
```

here's a screenshot of what ruby looks like at the moment:
![image](https://user-images.githubusercontent.com/609213/61658699-e98cce80-ac93-11e9-8867-c20bd9d7157f.png)
