### ISSUE TITLE
Opening file with pandoc syntax switches colorscheme to meh

### ISSUE THREAD

**Issue by enovid** [davidosomething/vim-colors-meh#6]
meh is my go-to colorscheme at night and during the day I want to use a light colorscheme, but everytime I open a pandoc file (e.g. markdown) the colorscheme switches back to meh.

**Comment by davidosomething** [comment]
there's special colors for pandoc since the vim-pandoc plugin doesn't follow meh's ideology

you can disable meh's pandoc overrides by setting 
`let g:meh_pandoc_enabled=0` before loading the plugin

vim-pandoc will then provide its own highlight config
